### ISSUE TITLE
更新使用者資訊時，輸入相同帳號及電子信箱導致錯誤

### ISSUE THREAD

**Issue by Shih-Hsuan** [NTOU-Auction/ntou-auction-java#87]
**問題描述：**

在更新使用者資訊時，遇到了一個錯誤。當我嘗試使用相同的帳號及電子信箱進行更新時，系統會產生一個錯誤訊息，但並未提供清晰的解決方案或錯誤訊息詳情。

**預期行為：**

我期望系統能夠處理更新使用者資訊的情況，即使使用相同的帳號及電子信箱。應該要有明確的錯誤訊息或指引，讓我知道應該如何解決這個問題。

**重現步驟：**

1. 登入帳號。
2. 前往使用者資訊頁面。
3. 嘗試更新使用相同的帳號及電子信箱。
4. 觀察錯誤訊息或不正常行為。

**附加資訊：**

我已經確認了我的輸入，並沒有錯誤。這個問題似乎是在系統處理相同帳號及電子信箱時出現的。請協助解決或提供更多相關資訊，謝謝！

**Comment by keke125** [comment]
已在 #89 修正此問題
